AnchorGenerator forces torch.arange in fp32 to allow export to onnx
zhiqwang/yolov5-rt-stack pull request #113
Opened 2021-06-09 15:27 UTC by dkloving

torch.arange cannot export to onnx with fp16 precision so it is necessary to force the operation into fp32 and then cast the result to the desired dtype.

2021-06-09 15:50 UTC, dkloving commented
Hmm I'm not sure why this is failing tests.

2021-06-09 16:37 UTC, zhiqwang commented on yolort/models/anchor_utils.py
> +            shifts_y = torch.arange(0, grid_height, dtype=torch.float32, device=device).type(dtype)
@dkloving , I guess that you could try the following instead

```python
shifts_x = torch.arange(0, grid_width, dtype=torch.float32, device=device).to(dtype=dtype)
shifts_y = torch.arange(0, grid_height, dtype=torch.float32, device=device).to(dtype=dtype)
```

2021-06-09 16:44 UTC, zhiqwang requested changes
@dkloving , Seems that the bug is due to the torchscript exporting, you should specify the type as I mentioned above, I'm not sure if the current modification will affect your needs, let me know what you think about this.

2021-06-24 00:13 UTC, dkloving commented
@zhiqwang thanks for the suggestion, it looks like that fixed it and this does meet our needs.

2021-06-24 01:50 UTC, merged

2021-06-24 01:51 UTC, zhiqwang reviewed
@dkloving LGTM, Thanks for your contributions!

2021-06-24 01:59 UTC, zhiqwang approved these changes
LGTM!